const state=window.NLState;
let pageLoadSeq=0;
let activePageSeq=0;
let toastTimer=null;
const $=s=>document.querySelector(s);
const renderIcons=()=>{if(window.lucide&&typeof window.lucide.createIcons==='function')window.lucide.createIcons({attrs:{'stroke-width':1.8}})};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const NAV_BY_ROLE={
  resident:[['dashboard','house','dashboard'],['payments','indian-rupee','payments'],['receipts','receipt-text','receipts'],['workorders','wrench','maintenance'],['complaints','circle-alert','complaints'],['notices','megaphone','notices']],
  vendor:[['dashboard','house','dashboard'],['workorders','check-circle-2','workorders']],
  admin:[['dashboard','house','dashboard'],['residents','users','residents'],['payments','indian-rupee','payments'],['workorders','wrench','workorders'],['complaints','circle-alert','complaints'],['vendors','hammer','vendors'],['vendorperformance','star','vendorPerformance'],['expenses','receipt','expenses'],['reports','chart-no-axes-combined','businessIntelligence'],['notices','megaphone','notices']]
};
const PAGE_NAMES=new Set(['dashboard','payments','receipts','workorders','complaints','notices','profile','residents','vendors','vendorperformance','expenses','reports']);
window.NAV_BY_ROLE=NAV_BY_ROLE;window.PAGE_NAMES=PAGE_NAMES;
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=String(msg||'');t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3000)}
async function api(path,opt={}){
  const method=String(opt.method||'GET').toUpperCase();
  const listBases=['/admin/users','/admin/vendors','/admin/expenses','/admin/payments','/admin/maintenance-bills','/bills','/payments','/complaints','/notices','/work-orders','/invoices'];
  if(method==='GET' && listBases.some(x=>path===x)){
    const f=state.listFilters?.[state.page]||{}; const u=new URL(path,location.origin);
    if(state.page==='residents' && path==='/admin/users')u.searchParams.set('role','resident');
    if(f.q)u.searchParams.set('q',f.q); if(f.status)u.searchParams.set('status',f.status);
    u.searchParams.set('page',String(f.page||1)); u.searchParams.set('per_page','20'); path=u.pathname+u.search;
  }
  return window.NLApi.request(path,opt)
}

function saveSession(d){window.NLState.saveSession(d)}
function logout(show=true){window.NLApi.clear();window.NLState.clearSession();if(window.NLVoice?.unmountMicButton)NLVoice.unmountMicButton();if(window.NLChatbot?.close)NLChatbot.close();document.getElementById('chatbotFab')?.remove();document.getElementById('chatbotPanel')?.remove();render();if(show)toast(i18n.t('loggedOut'))}

window.NLCore=window.NLCore||{};window.NLCore.onUnauthorized=()=>logout(false);
function render(){if(!state.token||!state.user)return renderAuth('login');state.role=state.user.role;renderShell()}
function renderAuth(mode='login'){let isLogin=mode==='login';$('#app').innerHTML=`<div class="auth"><section class="auth-art"><div class="brand">${i18n.t('appName')}<span> / community OS</span></div><div class="art-copy"><h1>${i18n.t('heroTitle')}</h1><p>${i18n.t('heroSubtitle')}</p><div class="art-grid"><div class="mini"><b>24/7</b><small>${i18n.t('digitalAccess')}</small></div><div class="mini"><b>₹</b><small>${i18n.t('securePayments')}</small></div></div></div></section><section class="auth-panel">${langSelectHtml()}<div class="auth-card">${isLogin?loginForm():registerForm()}</div></section></div>`;const authCard=$('.auth-card');if(!isLogin&&authCard)authCard.classList.add('register-card');bindAuth(mode);renderIcons()}
function roleButtons(selected){return `<div class="role-switch">${['resident','vendor','admin'].map(r=>`<button type="button" class="role-btn ${selected===r?'active':''}" data-role="${r}">${r==='resident'?'<i data-lucide="house"></i> '+i18n.t('resident'):r==='vendor'?'<i data-lucide="wrench"></i> '+i18n.t('vendor'):'<i data-lucide="shield-check"></i> '+i18n.t('admin')}</button>`).join('')}</div>`}
function loginForm(){return `<div class="brand" style="color:var(--accent)">${i18n.t('appName')}</div><h2>${i18n.t('welcomeBack')}</h2><p class="sub">${i18n.t('welcomeBackSub')}</p><div id="authError"></div>${roleButtons('resident')}<form id="loginForm"><div class="field"><label>${i18n.t('email')}</label><input id="email" type="email" required placeholder="you@example.com"></div><div class="field"><label>${i18n.t('password')}</label><input id="password" type="password" required placeholder="••••••••"></div><button class="primary">${i18n.t('enterWorkspace')} <i data-lucide="arrow-right"></i></button></form><div class="switch-link"><a id="forgotPassword">Forgot password?</a></div><div class="switch-link">${i18n.t('newHere')} <a id="toRegister">${i18n.t('register')}</a></div>`}
function registerForm(){return `<div class="brand" style="color:var(--accent)">${i18n.t('appName')}</div><h2>${i18n.t('createAccount')}</h2><p class="sub">${i18n.t('joinCommunitySub')}</p><div id="authError"></div><div class="role-switch"><button type="button" class="role-btn active"><i data-lucide="house"></i> ${i18n.t('resident')}</button></div><form id="registerForm" novalidate><div class="field"><label>${i18n.t('name')}</label><input id="name" required placeholder="${i18n.t('name')}"><div class="field-error" id="err-name"></div></div><div class="grid2"><div class="field"><label>${i18n.t('email')}</label><input id="email" type="email" required placeholder="you@example.com"><div class="field-error" id="err-email"></div></div><div class="field"><label>${i18n.t('phone')}</label><input id="phone" placeholder="9876543210"><div class="field-error" id="err-phone"></div></div></div><div class="field"><label>${i18n.t('apartment')}</label><input id="apartment" placeholder="A-204"></div><div class="field"><label>${i18n.t('password')}</label><input id="password" type="password" minlength="8" required placeholder="••••••••"><div class="field-error" id="err-password"></div></div><button class="primary">${i18n.t('register')} <i data-lucide="arrow-right"></i></button></form><div class="switch-link">${i18n.t('alreadyRegistered')} <a id="toLogin">${i18n.t('signIn')}</a></div>`}
function fieldError(id,msg){const el=document.getElementById('err-'+id);if(el)el.textContent=msg||''}
function clearFieldErrors(){document.querySelectorAll('.field-error').forEach(el=>el.textContent='')}
function validEmail(v){return /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(v)}
function validPhone(v){return !v || /^[6-9][0-9]{9}$/.test(v.replace(/\D/g,'').slice(-10))}
let selectedRole='resident';
function bindAuth(mode){selectedRole='resident';document.querySelectorAll('.role-btn[data-role]').forEach(b=>b.onclick=()=>{selectedRole=b.dataset.role;document.querySelectorAll('.role-btn[data-role]').forEach(x=>x.classList.toggle('active',x===b));});if($('#toRegister'))$('#toRegister').onclick=()=>renderAuth('register');if($('#toLogin'))$('#toLogin').onclick=()=>renderAuth('login');if($('#forgotPassword'))$('#forgotPassword').onclick=forgotPasswordModal;if(mode==='login')$('#loginForm').onsubmit=doLogin;else $('#registerForm').onsubmit=doRegister;if($('#langSelect'))$('#langSelect').onchange=e=>{i18n.setLanguage(e.target.value);renderAuth(mode)}}
function forgotPasswordModal(){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal"><button class="close" onclick="$('#modal').remove()">×</button><h3>Reset resident password</h3><p class="muted">Use the temporary password provided when your resident account was created.</p><form id="forgotForm"><div class="field"><label>Email</label><input id="fpEmail" type="email" required></div><div class="field"><label>Temporary password</label><input id="fpCurrent" type="password" required></div><div class="field"><label>New password</label><input id="fpNew" type="password" minlength="8" required></div><button class="primary">Change password</button></form></div></div>`);$('#forgotForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/auth/forgot-password',{method:'POST',body:JSON.stringify({email:$('#fpEmail').value,current_password:$('#fpCurrent').value,new_password:$('#fpNew').value})});$('#modal').remove();toast(d.message)}catch(x){toast(x.message)}}}
async function doLogin(e){e.preventDefault();const err=$('#authError');err.innerHTML='';try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value,role:selectedRole})});saveSession(d);render();toast(i18n.t('welcomeToApp'));}catch(x){err.innerHTML=`<div class="error">${esc(x.message)}</div>`}}
async function doRegister(e){e.preventDefault();const err=$('#authError');err.innerHTML='';clearFieldErrors();let ok=true;
    if(!$('#name').value.trim()){fieldError('name',i18n.t('requiredField'));ok=false}
    if(!validEmail($('#email').value.trim())){fieldError('email',i18n.t('invalidEmail'));ok=false}
    if(!validPhone($('#phone').value.trim())){fieldError('phone',i18n.t('invalidPhone'));ok=false}
    if($('#password').value.length<8){fieldError('password',i18n.t('weakPassword'));ok=false}
    if(!ok)return;
    try{const d=await api('/auth/register',{method:'POST',body:JSON.stringify({name:$('#name').value,email:$('#email').value,phone:$('#phone').value,apartment:$('#apartment').value,password:$('#password').value,role:'resident'})});toast(d.message);renderAuth('login');}catch(x){err.innerHTML=`<div class="error">${esc(x.message)}</div>`}}
function navItems(){return (NAV_BY_ROLE[state.role]||NAV_BY_ROLE.resident).map(([page,icon,label])=>[page,`<i data-lucide="${icon}"></i>`,label])}
function langSelectHtml(){return `<select class="lang-select" id="langSelect">${i18n.LANGUAGES.map(([code,label])=>`<option value="${code}" ${i18n.getLanguage()===code?'selected':''}>${label}</option>`).join('')}</select>`}
async function renderBell(){const box=$('#bellCount');try{const d=await api('/notifications');if(box)box.innerHTML=d.unread_count?`<span class="bell-dot">${Math.min(Number(d.unread_count)||0,99)}</span>`:'';const panel=$('#notifPanel');if(panel)panel.dataset.items=JSON.stringify(d.notifications||[])}catch(e){if(box)box.innerHTML=''}}
function renderNotifPanel(){const panel=$('#notifPanel');if(!panel)return;let items=[];try{items=JSON.parse(panel.dataset.items||'[]')}catch{}panel.innerHTML=`<div class="notif-panel-head"><h4>${i18n.t('notifications')}</h4><button type="button" class="text-button" id="markAllRead">${i18n.t('markAllRead')}</button></div>${items.length?items.map(n=>`<button type="button" class="notif-item ${n.is_read?'':'unread'}" data-id="${Number(n.id)||0}"><b>${esc(n.title)}</b><p>${esc(n.message)}</p></button>`).join(''):`<div class="notif-item"><p>${i18n.t('noNotifications')}</p></div>`}`;panel.querySelectorAll('.notif-item[data-id]').forEach(el=>el.onclick=async()=>{try{await api(`/notifications/${el.dataset.id}/read`,{method:'PATCH'});await renderBell();renderNotifPanel()}catch(e){toast(e.message)}});$('#markAllRead')?.addEventListener('click',async e=>{e.stopPropagation();try{await api('/notifications/read-all',{method:'PATCH'});await renderBell();renderNotifPanel()}catch(x){toast(x.message)}})}
function closeNotifOnOutside(e){const p=$('#notifPanel');const b=$('#bellBtn');if(p&&p.style.display==='block'&&!p.contains(e.target)&&!b?.contains(e.target))p.style.display='none'}
function updateNavActive(){
  document.querySelectorAll('.nav [data-page]').forEach(btn=>{
    const active=btn.dataset.page===state.page;
    btn.classList.toggle('active',active);
    btn.setAttribute('aria-current',active?'page':'false');
  });
}
function renderShell(){
  const items=navItems();
  $('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="side-brand"><div class="brand">${i18n.t('appName')}</div><small>${i18n.t(state.role)?.toUpperCase()||state.role.toUpperCase()} ${i18n.t('workspaceLabel')}</small>${langSelectHtml()}</div><nav class="nav" aria-label="Primary">${items.map(([page,icon,label])=>`<button type="button" class="${state.page===page?'active':''}" data-page="${page}" aria-current="${state.page===page?'page':'false'}"><span class="nav-icon">${icon}</span><span class="nav-label">${i18n.t(label)}</span></button>`).join('')}</nav></aside><main class="main"><div class="topbar ${state.role==='vendor'?'vendor-topbar':''}"><div class="topbar-copy">${state.role==='vendor'?'':`<h1>${state.role==='resident'?i18n.t('goodEvening')+', '+esc(state.user.name.split(' ')[0])+' <i data-lucide="hand"></i>':i18n.t('adminControlRoom')}</h1><p>${i18n.t('everythingInOnePlace')}</p>`}</div><div class="topbar-actions"><div class="bell-wrap"><button type="button" class="bell-btn" id="bellBtn" aria-label="${i18n.t('notifications')}"><i data-lucide="bell"></i><span id="bellCount"></span></button><div class="notif-panel" id="notifPanel" hidden></div></div><span class="topbar-divider" aria-hidden="true"></span><button type="button" class="profile-top" data-page="profile" aria-label="${i18n.t('profile')}"><span class="avatar">${esc((state.user.name||'U')[0].toUpperCase())}</span><span class="profile-top-copy"><b>${esc(state.user.name)}</b><small>${esc(state.role==='vendor' ? (state.user.job_title || i18n.t('vendor')) : i18n.t(state.role))}</small></span><i data-lucide="chevron-down" class="profile-chevron"></i></button><button type="button" class="logout-top" id="logout" aria-label="${i18n.t('logout')}" title="${i18n.t('logout')}"><i data-lucide="log-out"></i><span>${i18n.t('logout')}</span></button></div></div><div id="content"></div></main></div>`;
  $('#app').onclick=e=>{const nav=e.target.closest('[data-page]');if(nav){e.preventDefault();go(nav.dataset.page)}};
  $('#logout').onclick=()=>logout();
  $('#langSelect').onchange=e=>{i18n.setLanguage(e.target.value);renderShell();window.NLVoice?.refreshLabel?.();window.NLChatbot?.refreshLabel?.()};
  $('#bellBtn').onclick=async()=>{const p=$('#notifPanel');if(!p)return;const open=!p.hidden;p.hidden=open;if(!open){await renderBell();renderNotifPanel();p.hidden=false}};
  document.removeEventListener('click',closeNotifOnOutside);document.addEventListener('click',closeNotifOnOutside);
  renderBell();window.NLChatbot?.mount?.();renderIcons();loadPage();
}
const LIST_CONFIG={
  residents:{endpoint:'/admin/users',export:'residents',placeholder:'Search residents by name, email or unit'},
  vendors:{endpoint:'/admin/vendors',export:'vendors',placeholder:'Search vendors by name, service or contact'},
  expenses:{endpoint:'/admin/expenses',export:'expenses',placeholder:'Search expenses by category or description'},
  complaints:{endpoint:'/complaints',export:'complaints',placeholder:'Search complaints'},
  notices:{endpoint:'/notices',export:'notices',placeholder:'Search notices'},
  workorders:{endpoint:'/work-orders',export:'work-orders',placeholder:'Search work orders'},
  payments:{endpoint:state.role==='admin'?'/admin/payments':'/payments',export:state.role==='admin'?'payments':null,placeholder:'Search payments'},
  receipts:{endpoint:'/payments',export:null,placeholder:'Search receipts'},
};
state.listFilters=state.listFilters||{};
function exportQuery(resource, format, page){
  const f=state.listFilters?.[page]||{}; const u=new URL(`/admin/export/${resource}`,location.origin); u.searchParams.set('format',format);
  if(f.q)u.searchParams.set('q',f.q); if(f.status)u.searchParams.set('status',f.status); return u.pathname+u.search;
}
async function exportList(resource, format, page){
  try{
    const response=await window.NLApi.download(exportQuery(resource,format,page));
    const blob=await response.blob(); const disposition=response.headers.get('Content-Disposition')||'';
    const match=disposition.match(/filename="?([^";]+)"?/i); const filename=match?.[1]||`nestledger_${resource}.${format}`;
    const url=URL.createObjectURL(blob); const link=document.createElement('a'); link.href=url; link.download=filename; document.body.appendChild(link); link.click(); link.remove(); setTimeout(()=>URL.revokeObjectURL(url),1000);
    toast(`${format.toUpperCase()} export ready`);
  }catch(e){toast(e.message||'Export failed')}
}
function exportButtons(resource,page){return resource?`<div class="export-actions"><span>Export</span><button type="button" class="secondary" onclick="exportList('${resource}','csv','${page}')"><i data-lucide="file-text"></i> CSV</button><button type="button" class="secondary" onclick="exportList('${resource}','xlsx','${page}')"><i data-lucide="file-spreadsheet"></i> Excel</button></div>`:''}
function listControls(page){
  const cfg=LIST_CONFIG[page]; if(!cfg)return; const endpoint=(page==='payments'&&state.role==='admin')?'/admin/payments':cfg.endpoint; const f=state.listFilters[page]||{page:1,q:'',status:''}; state.listFilters[page]=f;
  const meta=window.NLApi.meta(endpoint)||{};
  const host=$('#content'); const title=host?.querySelector('.page-title'); if(!title)return;
  const old=host.querySelector('.list-controls'); if(old)old.remove();
  const statuses=page==='complaints'?['','open','in_progress','resolved','closed']:page==='workorders'?['','open','accepted','in_progress','completed','cancelled']:page==='payments'||page==='receipts'?['','created','paid','failed']:page==='vendors'?['','active','inactive']:[];
  const el=document.createElement('div'); el.className='list-controls'; el.innerHTML=`<div class="list-search"><i data-lucide="search"></i><input id="listSearch" value="${esc(f.q)}" placeholder="${cfg.placeholder}" aria-label="Search"></div>${statuses.length?`<select id="listStatus" aria-label="Filter by status">${statuses.map(x=>`<option value="${x}">${x?' '+statusLabel(x):'All statuses'}</option>`).join('')}`:''}<div class="list-pages"><button type="button" class="secondary" id="listPrev" ${!meta.has_prev?'disabled':''}>‹</button><span>${meta.total?`${meta.page} / ${meta.pages}`:'0 results'}</span><button type="button" class="secondary" id="listNext" ${!meta.has_next?'disabled':''}>›</button></div>${exportButtons(cfg.export,page)}`;
  title.insertAdjacentElement('afterend',el);
  const search=el.querySelector('#listSearch'); let timer; search.oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{f.q=search.value.trim();f.page=1;loadPage()},250)};
  const sel=el.querySelector('#listStatus'); if(sel){sel.value=f.status||'';sel.onchange=()=>{f.status=sel.value;f.page=1;loadPage()}}
  el.querySelector('#listPrev')?.addEventListener('click',()=>{if(f.page>1){f.page--;loadPage()}}); el.querySelector('#listNext')?.addEventListener('click',()=>{if(meta.has_next){f.page++;loadPage()}}); renderIcons();
}
async function loadPage(options={}){
  const c=$('#content');if(!c)return;
  const silent=Boolean(options.silent);
  const seq=++pageLoadSeq;
  // Background refreshes must never replace a usable page with a disruptive
  // full-page "Loading live data" state. Only show the loader on first load
  // (or when there is no content to preserve).
  const hasContent=Boolean(c.innerHTML.trim());
  if(!silent || !hasContent){
    c.innerHTML=`<div class="panel empty page-loading"><span class="loading-spinner" aria-hidden="true"></span><span>${i18n.t('loading')}</span></div>`;
    renderIcons();
  }
  const loader=PAGE_LOADERS[state.page]||PAGE_LOADERS.dashboard;
  try{await loader(c); listControls(state.page)}catch(e){
    if(e.name==='AbortError'||seq!==pageLoadSeq)return;
    // During a silent refresh, keep the last good screen if the refresh fails.
    if(silent && hasContent){toast(e.message||i18n.t('requestFailed'));return}
    c.innerHTML=`<div class="panel error-state"><i data-lucide="triangle-alert"></i><h3>${esc(e.message)}</h3><button class="secondary" type="button" onclick="loadPage()">${i18n.t('retry')||'Retry'}</button></div>`;
  }finally{if(seq===pageLoadSeq)renderIcons()}
}
function go(p){return window.NLRouter.navigate(p)}
function viewResidentPayments(name){state.listFilters=state.listFilters||{};state.listFilters.payments=state.listFilters.payments||{page:1,q:'',status:''};state.listFilters.payments.q=decodeURIComponent(name||'');state.listFilters.payments.page=1;const m=$('#residentDetailModal');if(m)m.remove();go('payments')}

async function dashboard(c){
    const d=await api('/dashboard');
    const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
    if(state.role==='resident'){
        const due=d.due||0;
        const paid=d.paid||0;
        const bills=d.pending_bills||[];
        c.innerHTML=`
        <div class="page-title"><span class="eyebrow">${i18n.t('myHome')}</span><h2>${esc(state.user.apartment||i18n.t('apartmentNotAssigned'))}</h2><p>${i18n.t('residentAccountTagline')}</p></div>
        <section class="hero hero-phase2"><div><div class="eyebrow">${i18n.t('currentMaintenanceDue')}</div><h2>${due?i18n.t('actionRequired'):i18n.t('allClear')}</h2><p>${due?`${money(due)} ${i18n.t('dueLabel')}`:i18n.t('verifiedPayments')}</p></div><div class="hero-amount"><small>${i18n.t('totalPaid')}</small><b>${money(paid)}</b></div></section>
        <div class="cards">
          <div class="stat"><small>${i18n.t('maintenanceDue')}</small><b>${money(due)}</b><em>${due?i18n.t('actionRequired'):i18n.t('allClear')}</em></div>
          <div class="stat"><small>${i18n.t('totalPaid')}</small><b>${money(paid)}</b><em>${d.paid_count||0} ${i18n.t('verifiedPayments')}</em></div>
          <div class="stat"><small>${i18n.t('openRequests').toUpperCase()}</small><b>${d.active_requests||0}</b><em>${i18n.t('inThePipeline')}</em></div>
          <div class="stat"><small>${i18n.t('complaints').toUpperCase()}</small><b>${d.complaints||0}</b><em>${i18n.t('raisedByYou')}</em></div>
        </div>
        <div class="phase2-grid">
          <div class="panel"><div class="panel-head"><div><h3>${i18n.t('maintenanceRequests')}</h3><p class="muted">${i18n.t('inThePipeline')}</p></div><button class="secondary" onclick="go('workorders')"><i data-lucide="arrow-up-right"></i>${i18n.t('viewAll')}</button></div>${(d.work_orders||[]).length?d.work_orders.map(residentOrderCard).join(''):`<div class="empty-state"><i data-lucide="inbox"></i><h4>${i18n.t('noMaintenanceRequestsYet')}</h4><p>${i18n.t('requestMaintenance')}</p><button class="secondary" onclick="go('workorders')">${i18n.t('requestMaintenance')}</button></div>`}</div>
          <div class="panel"><div class="panel-head"><div><h3>${i18n.t('payments')}</h3><p class="muted">${i18n.t('paymentHistory')}</p></div><button class="secondary" onclick="go('payments')">${i18n.t('viewAll')}</button></div>${bills.length?bills.map(b=>`<div class="list-row compact"><div><h4>${esc(b.description)}</h4><p>${esc(b.month)} · ${i18n.t('dueLabel')} ${esc(b.due_date)}</p></div><div><strong>${money(b.amount)}</strong><br><button class="pay" onclick="payBill(${b.id})">${i18n.t('payNow')} <i data-lucide="arrow-right"></i></button></div></div>`).join(''):`<div class="empty-state"><i data-lucide="badge-check"></i><h4>${i18n.t('allClear')}</h4><p>${i18n.t('noMaintenanceBills')}</p></div>`}</div>
        </div>
        <div class="panel"><div class="panel-head"><div><h3>${i18n.t('notices')}</h3><p class="muted">${i18n.t('noticesSubtitle')}</p></div><button class="secondary" onclick="go('notices')">${i18n.t('viewAll')}</button></div><div class="notice-strip">${(d.recent_notices||[]).map(n=>`<article><span class="tag">${esc(n.tag)}</span><h4>${esc(n.title)}</h4><p>${esc(n.body)}</p></article>`).join('')||`<div class="empty-state"><i data-lucide="megaphone"></i><h4>${i18n.t('noNoticesYet')}</h4></div>`}</div></div>`;
    }else if(state.role==='vendor'){
        c.innerHTML=`<div class="page-title vendor-page-title"><h2>${i18n.t('vendorWorkspace')}</h2><p>${i18n.t('vendorHubSubtitle')}</p></div><section class="hero hero-phase2 vendor-hero"><div class="vendor-hero-main"><div class="eyebrow">${i18n.t('openJobsAvailable')}</div><h2>${d.open_jobs_count||0}</h2><p>${i18n.t('awaitingVendor')}</p></div><div class="hero-amount vendor-hero-side"><small>${i18n.t('activeJobs')}</small><b>${d.work_orders.length}</b><span>${i18n.t('acceptedInProgress')}</span></div></section><div class="cards"><div class="stat"><small>${i18n.t('activeJobs')}</small><b>${d.work_orders.length}</b><em>${i18n.t('acceptedInProgress')}</em></div><div class="stat"><small>${i18n.t('openOnBoard')}</small><b>${d.open_jobs_count||0}</b><em>${i18n.t('awaitingVendor')}</em></div><div class="stat"><small>Pending quotes</small><b>${d.pending_quotes||0}</b><em>Awaiting resident decision</em></div><div class="stat"><small>Completed</small><b>${d.completed_jobs||0}</b><em>${d.unpaid_jobs||0} awaiting payment</em></div></div><div class="phase2-grid"><div class="panel"><div class="panel-head"><div><h3>${i18n.t('myActiveJobs')}</h3><p class="muted">${i18n.t('acceptedInProgress')}</p></div><button class="secondary" onclick="go('workorders')">${i18n.t('openBoard')}</button></div>${d.work_orders.length?d.work_orders.map(w=>orderCard(w)).join(''):`<div class="empty-state"><i data-lucide="wrench"></i><h4>${i18n.t('noActiveJobs')}</h4><p>${i18n.t('nothingOpenNow')}</p></div>`}</div><div class="panel"><div class="panel-head"><div><h3>${i18n.t('newOnBoard')}</h3><p class="muted">${i18n.t('openJobsAvailable')}</p></div></div>${(d.open_jobs||[]).length?d.open_jobs.map(w=>orderCard(w)).join(''):`<div class="empty-state"><i data-lucide="search-x"></i><h4>${i18n.t('nothingOpenNow')}</h4></div>`}</div></div>`;
    }else{
        const f=d.financials||{};
        const cb=d.complaint_breakdown||{};
        const total=Math.max(Number(f.total_billed||0),1);
        const collectionPct=Math.min(100,Math.round((Number(f.total_collected||0)/total)*100));
        const activity=(d.recent_activity||[]).slice(0,8).map(e=>`<div class="activity-item"><span class="activity-icon"><i data-lucide="${e.kind==='payment'?'indian-rupee':e.kind==='complaint'?'circle-alert':e.kind==='workorder'?'wrench':'user-round-plus'}"></i></span><div><b>${esc(e.title)}</b><p>${esc(e.detail)}</p></div><time>${e.created_at?new Date(e.created_at).toLocaleDateString('en-IN'):''}</time></div>`).join('')||`<div class="empty-state"><i data-lucide="clock-3"></i><h4>${i18n.t('noData')}</h4></div>`;
        c.innerHTML=`
          <div class="page-title admin-title"><span class="eyebrow">${i18n.t('operations')}</span><h2>${i18n.t('controlRoomTitle')}</h2><p>${i18n.t('controlRoomSubtitle')}</p></div>
          <section class="hero admin-hero">
            <div class="admin-hero-metric"><span>${i18n.t('collection')}</span><b>${money(f.total_collected)}</b><small>${collectionPct}% ${i18n.t('collection')}</small></div>
            <div class="admin-hero-center"><i data-lucide="landmark"></i><strong>Community finance</strong><span>${money(f.balance)} balance after expenses</span></div>
            <div class="admin-hero-metric right"><span>${i18n.t('expenses')}</span><b>${money(f.total_expenses)}</b><small>${money(f.total_pending)} pending</small></div>
          </section>
          <div class="cards admin-stats">
            <div class="stat"><small>${i18n.t('residents')}</small><b>${d.residents}</b><em>${i18n.t('registeredLabel')}</em></div>
            <div class="stat"><small>${i18n.t('vendors')}</small><b>${d.vendors}</b><em>${i18n.t('registeredLabel')}</em></div>
            <div class="stat"><small>${i18n.t('openComplaintsLabel')}</small><b>${d.open_complaints}</b><em>${i18n.t('needsAttention')}</em></div>
            <div class="stat"><small>${i18n.t('openWorkOrdersLabel')}</small><b>${d.open_work_orders||0}</b><em>${i18n.t('awaitingVendor')}</em></div>
          </div>
          <div class="admin-overview-grid">
            <section class="panel finance-panel compact-panel"><div class="panel-head"><div><span class="eyebrow">${i18n.t('financialOverview')}</span><h3>${i18n.t('financialOverview')}</h3></div><button type="button" class="text-button" onclick="go('payments')">${i18n.t('viewAll')} <i data-lucide="arrow-up-right"></i></button></div><div class="progress-track"><span style="width:${collectionPct}%"></span></div><div class="finance-lines"><div><span>${i18n.t('collection')}</span><b>${money(f.total_collected)}</b></div><div><span>${i18n.t('pending')}</span><b>${money(f.total_pending)}</b></div><div><span>${i18n.t('expenses')}</span><b>${money(f.total_expenses)}</b></div><div><span>${i18n.t('balance')}</span><b>${money(f.balance)}</b></div></div></section>
            <section class="panel complaint-panel compact-panel"><div class="panel-head"><div><span class="eyebrow">${i18n.t('operations')}</span><h3>${i18n.t('complaints')}</h3></div><button type="button" class="text-button" onclick="go('complaints')">${i18n.t('viewAll')} <i data-lucide="arrow-up-right"></i></button></div><div class="status-bars">${[['open',cb.open],['in_progress',cb.in_progress],['resolved',cb.resolved],['closed',cb.closed]].map(([k,v])=>`<div><span>${statusLabel(k)}</span><b>${v||0}</b><i><em style="width:${Math.min(100,(Number(v||0)/Math.max(1,d.open_complaints+Number(cb.resolved||0)+Number(cb.closed||0)))*100)}%"></em></i></div>`).join('')}</div></section>
          </div>
          <div class="admin-lower-grid">
            <section class="panel activity-panel"><div class="panel-head"><div><span class="eyebrow">${i18n.t('systemStatus')}</span><h3>Recent activity</h3></div></div><div class="activity-list">${activity}</div></section>
            <section class="panel admin-shortcuts compact-panel"><div class="panel-head"><div><span class="eyebrow">Quick actions</span><h3>${i18n.t('adminShortcuts')}</h3></div></div><div class="shortcut-row">${[['residents','users'],['payments','indian-rupee'],['workorders','wrench'],['expenses','receipt-text'],['notices','megaphone'],['vendors','hard-hat']].map(([page,icon])=>`<button type="button" class="shortcut" onclick="go('${page}')"><i data-lucide="${icon}"></i><span>${i18n.t(page)}</span></button>`).join('')}</div></section>
          </div>`;
    }
    renderIcons();
}
function financeBlock(f){if(!f)return'';return `<div class="page-title" style="margin-bottom:8px"><h2>${i18n.t('financialOverview')}</h2></div><div class="finance-grid"><div class="finance-stat"><small>${i18n.t('totalBilled').toUpperCase()}</small><b>₹${f.total_billed.toLocaleString('en-IN')}</b></div><div class="finance-stat"><small>${i18n.t('collected').toUpperCase()}</small><b>₹${f.total_collected.toLocaleString('en-IN')}</b></div><div class="finance-stat"><small>${i18n.t('pending').toUpperCase()}</small><b>₹${f.total_pending.toLocaleString('en-IN')}</b></div><div class="finance-stat"><small>${i18n.t('expenses').toUpperCase()}</small><b>₹${f.total_expenses.toLocaleString('en-IN')}</b></div><div class="finance-stat"><small>${i18n.t('balance').toUpperCase()}</small><b>₹${f.balance.toLocaleString('en-IN')}</b></div><div class="finance-stat"><small>${i18n.t('collectionRate').toUpperCase()}</small><b>${f.collection_rate}%</b><div class="progress-track"><div class="progress-fill" style="width:${Math.min(f.collection_rate,100)}%"></div></div></div></div>`}
async function vendorperformance(c){const d=await api('/admin/vendor-performance');c.innerHTML=`<div class="page-title"><h2>${i18n.t('vendorPerformance')}</h2><p>${i18n.t('vendorPerfSubtitle')}</p></div>${d.vendor_performance.length?d.vendor_performance.map(v=>`<div class="perf-card"><div class="perf-head"><b>${esc(v.vendor.name)}</b><span class="perf-score">${v.score}/100</span></div><div class="perf-metrics"><div><small>${i18n.t('completed')}</small><b>${v.completed_jobs}</b></div><div><small>${i18n.t('cancelledLabel')}</small><b>${v.cancelled_jobs}</b></div><div><small>${i18n.t('completionRate')}</small><b>${v.completion_rate}%</b></div><div><small>${i18n.t('activeJobs')}</small><b>${v.active_jobs}</b></div><div><small>${i18n.t('avgRatingLabel')}</small><b>${v.vendor.average_rating!=null?'★ '+v.vendor.average_rating:'—'}</b></div></div>${v.average_completion_hours!=null?`<p class="muted" style="margin-top:8px;font-size:12px">${i18n.t('avgCompletionTime')}: ${v.average_completion_hours}h</p>`:''}</div>`).join(''):`<div class="panel empty">${i18n.t('noVendorsYet')}</div>`}`}
function statusLabel(s){if(!s)return'';const key='status'+String(s).split('_').map(w=>w?w[0].toUpperCase()+w.slice(1):'').join('');return i18n.t(key)!==key?i18n.t(key):s.replace('_',' ')}
function orderCard(w){return `<div class="list-card"><div class="list-row"><div><h4>${esc(w.title)}</h4><p>${esc(w.category||i18n.t('generalCategory'))} · ${esc(w.vendor_name)} · ${i18n.t('dueLabel')} ${esc(w.due_date||'—')}</p></div><div style="text-align:right"><span class="badge ${esc(w.status)}">${statusLabel(w.status)}</span>${w.amount?`<div class="amount" style="margin-top:6px">₹${Number(w.amount).toLocaleString('en-IN')}</div>`:''}</div></div></div>`}

function residentOrderCard(w){const assigned=w.vendor_id?`<div class="notice" style="margin:10px 0 0;padding:11px 14px;background:#f4f7f4"><span class="tag">${w.status==='completed'?i18n.t('completedByLabel'):i18n.t('pickedUpBy')}</span><h3 style="font-size:14px;margin:4px 0 2px">${esc(w.vendor_name)}${w.vendor_service?' · '+esc(w.vendor_service):''}</h3><p>${w.vendor_contact?'<i data-lucide="phone"></i> '+esc(w.vendor_contact):i18n.t('noContactOnFile')}${w.completed_at?' · '+i18n.t('completedAtLabel')+' '+new Date(w.completed_at).toLocaleString('en-IN'):w.accepted_at?' · '+i18n.t('acceptedAtLabel')+' '+new Date(w.accepted_at).toLocaleString('en-IN'):''}</p></div>`:'';const ratingBlock=w.status==='completed'&&w.vendor_id?(w.rating?`<div class="notice" style="margin:10px 0 0;padding:11px 14px;background:#fff8e6"><span class="tag">${i18n.t('yourRatingLabel')}</span><h3 style="font-size:16px;margin:4px 0 2px;letter-spacing:2px;color:#b37a16">${'★'.repeat(w.rating.stars)}${'☆'.repeat(5-w.rating.stars)}</h3>${w.rating.remarks?`<p>${esc(w.rating.remarks)}</p>`:''}</div>`:`<div class="btn-row"><button class="secondary" onclick="rateVendorModal(${w.id})">${i18n.t('rateVendorBtn')}</button></div>`):'';const quotesBtn=w.status==='open'&&w.quotes_count?`<div class="btn-row"><button class="secondary" onclick="quotesModal(${w.id})">${i18n.t('viewQuotesBtn')} (${w.quotes_count})</button></div>`:'';return `<div class="list-card"><div class="list-row"><div><h4>${esc(w.title)}</h4><p>${esc(w.category||i18n.t('generalCategory'))} ${w.due_date?'· '+i18n.t('neededBy')+' '+esc(w.due_date):''}</p>${w.description?`<p>${esc(w.description)}</p>`:''}</div><div style="text-align:right"><span class="badge ${esc(w.status)}">${statusLabel(w.status)}</span>${w.amount?`<div class="amount" style="margin-top:6px">₹${Number(w.amount).toLocaleString('en-IN')}</div>`:''}</div></div>${assigned}${ratingBlock}${quotesBtn}${w.status==='open'?`<div class="btn-row"><button class="cancel" onclick="cancelWorkOrder(${w.id})">${i18n.t('cancelRequest')}</button></div>`:''}${w.vendor_id&&w.amount&&['accepted','in_progress','completed'].includes(w.status)?(w.payment_status==='paid'?`<div class="btn-row"><span class="badge paid">${i18n.t('vendorPaymentPaid')}</span></div>`:`<div class="btn-row"><button class="pay" onclick="payVendor(${w.id})">${i18n.t('payVendorBtn')} ₹${Number(w.amount).toLocaleString('en-IN')} →</button></div>`):''}</div>`}

function vendorOpenCard(w){const mq=w.my_quote;const quoteBlock=mq?`<div class="notice" style="margin:10px 0 0;padding:10px 14px;background:#eef0ff"><span class="tag">${i18n.t('yourQuoteLabel')}</span><h3 style="font-size:15px;margin:4px 0 2px">₹${Number(mq.amount).toLocaleString('en-IN')}</h3>${mq.note?`<p>${esc(mq.note)}</p>`:''}</div>`:'';const quoteBtn=mq?`<button class="secondary" onclick="quoteModal(${w.id})">${i18n.t('updateQuote')}</button><button class="cancel" onclick="withdrawQuote(${w.id},${mq.id})">${i18n.t('withdrawQuote')}</button>`:`<button class="secondary" onclick="quoteModal(${w.id})">${i18n.t('submitQuote')}</button>`;return `<div class="list-card"><div class="list-row"><div><h4>${esc(w.title)}</h4><p>${esc(w.category||i18n.t('generalCategory'))} · ${esc(w.apartment||i18n.t('apartmentNA'))} ${w.due_date?'· '+i18n.t('neededBy')+' '+esc(w.due_date):''}</p>${w.description?`<p>${esc(w.description)}</p>`:''}</div><div style="text-align:right">${w.amount?`<div class="amount">₹${Number(w.amount).toLocaleString('en-IN')}</div>`:''}</div></div>${quoteBlock}<div class="btn-row"><button class="accept" onclick="acceptWorkOrder(${w.id})">${i18n.t('acceptJob')} →</button>${quoteBtn}</div></div>`}

function vendorMineCard(w){const payment=w.payment_status==='paid'?`<span class="badge paid">${i18n.t('vendorPaymentPaid')}</span>`:(w.amount?`<span class="badge">${i18n.t('statusPending')}</span>`:'');return `<div class="list-card"><div class="list-row"><div><h4>${esc(w.title)}</h4><p>${esc(w.category||i18n.t('generalCategory'))}${w.resident_name?' · '+esc(w.resident_name):''}${w.apartment?' · '+esc(w.apartment):''}${w.due_date?' · '+i18n.t('neededBy')+' '+esc(w.due_date):''}</p>${w.description?`<p>${esc(w.description)}</p>`:''}</div><div style="text-align:right"><span class="badge ${esc(w.status)}">${statusLabel(w.status)}</span>${w.amount?`<div class="amount" style="margin-top:6px">₹${Number(w.amount).toLocaleString('en-IN')}</div>`:''}</div></div>${payment?`<div class="btn-row">${payment}</div>`:''}${w.status==='accepted'?`<div class="btn-row"><button class="start" onclick="setWorkOrderStatus(${w.id},'in_progress')">${i18n.t('start')}</button><button class="cancel" onclick="withdrawWorkOrder(${w.id})">${i18n.t('withdraw')}</button></div>`:''}${w.status==='in_progress'?`<div class="btn-row"><button class="finish" onclick="setWorkOrderStatus(${w.id},'completed')">${i18n.t('markComplete')} →</button></div>`:''}</div>`}

function adminOrderCard(w){const ratingLine=w.rating?`<p class="muted" style="font-size:11px;margin-top:6px">${i18n.t('ratingLabel')}: ${'★'.repeat(w.rating.stars)}${'☆'.repeat(5-w.rating.stars)}</p>`:'';const quotesBtn=w.status==='open'?`<div class="btn-row"><button class="secondary" onclick="quotesModal(${w.id})">${i18n.t('viewQuotesBtn')}${w.quotes_count?` (${w.quotes_count})`:''}</button></div>`:'';return `<div class="list-card"><div class="list-row"><div><h4>${esc(w.title)}</h4><p>${esc(w.category||i18n.t('generalCategory'))} · ${esc(w.resident_name||i18n.t('postedByAdmin'))}${w.apartment?' ('+esc(w.apartment)+')':''} → ${esc(w.vendor_name)}</p>${w.description?`<p>${esc(w.description)}</p>`:''}</div><div style="text-align:right"><span class="badge ${esc(w.status)}">${statusLabel(w.status)}</span>${w.amount?`<div class="amount" style="margin-top:6px">₹${Number(w.amount).toLocaleString('en-IN')}</div>`:''}</div></div>${ratingLine}${quotesBtn}</div>`}

async function acceptWorkOrder(id){try{await api('/work-orders/'+id+'/accept',{method:'PATCH'});toast(i18n.t('jobAccepted')+' <i data-lucide="party-popper"></i>');loadPage()}catch(e){toast(e.message)}}
async function setWorkOrderStatus(id,status){try{await api('/work-orders/'+id+'/status',{method:'PATCH',body:JSON.stringify({status})});toast(status==='completed'?i18n.t('jobMarkedComplete')+' <i data-lucide="party-popper"></i>':i18n.t('statusUpdated'));loadPage()}catch(e){toast(e.message)}}
async function cancelWorkOrder(id){if(!confirm(i18n.t('confirmCancelRequest')))return;setWorkOrderStatus(id,'cancelled')}
async function withdrawWorkOrder(id){if(!confirm(i18n.t('confirmWithdraw')))return;try{await api(`/work-orders/${id}/withdraw`,{method:'PATCH'});toast(i18n.t('withdrewFromJob'));loadPage()}catch(e){toast(e.message)}}

function quoteModal(wid){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal"><button class="close" onclick="$('#modal').remove()">×</button><h3>${i18n.t('submitQuoteModalTitle')}</h3><form id="qf"><div class="field"><label>${i18n.t('quoteAmountLabel')}</label><input id="qamt" type="number" min="1" step="1" required placeholder="₹"></div><div class="field"><label>${i18n.t('quoteNoteLabel')}</label><textarea id="qnote" rows="3" placeholder="${i18n.t('quoteNotePlaceholder')}"></textarea></div><button class="primary">${i18n.t('submitQuoteBtn')}</button></form></div></div>`);$('#qf').onsubmit=async e=>{e.preventDefault();try{await api(`/work-orders/${wid}/quotes`,{method:'POST',body:JSON.stringify({amount:$('#qamt').value,note:$('#qnote').value})});$('#modal').remove();toast(i18n.t('quoteSubmitted'));loadPage()}catch(x){toast(x.message)}}}

async function quotesModal(wid){let quotes=[];try{const d=await api(`/work-orders/${wid}/quotes`);quotes=d.quotes}catch(e){toast(e.message);return}document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal"><button class="close" onclick="$('#modal').remove()">×</button><h3>${i18n.t('quotesReceivedTitle')}</h3>${quotes.length?quotes.map(q=>`<div class="list-card"><div class="list-row"><div><h4>${esc(q.vendor_name)}</h4><p>${esc(q.vendor_service||'')}${q.vendor_contact?' · <i data-lucide="phone"></i> '+esc(q.vendor_contact):''}</p>${q.note?`<p>${esc(q.note)}</p>`:''}</div><div style="text-align:right"><div class="amount">₹${Number(q.amount).toLocaleString('en-IN')}</div><span class="badge ${esc(q.status)}">${statusLabel(q.status)}</span></div></div>${q.status==='pending'?`<div class="btn-row"><button class="accept" onclick="acceptQuote(${wid},${q.id})">${i18n.t('acceptQuoteBtn')}</button><button class="cancel" onclick="rejectQuote(${wid},${q.id})">${i18n.t('declineQuoteBtn')}</button></div>`:''}</div>`).join(''):`<div class="empty">${i18n.t('noQuotesYet')}</div>`}</div></div>`)}

async function acceptQuote(wid,qid){if(!confirm(i18n.t('confirmAcceptQuote')))return;try{await api(`/work-orders/${wid}/quotes/${qid}/accept`,{method:'PATCH'});const m=$('#modal');if(m)m.remove();toast(i18n.t('quoteAccepted'));loadPage()}catch(e){toast(e.message)}}

async function rejectQuote(wid,qid){try{await api(`/work-orders/${wid}/quotes/${qid}/reject`,{method:'PATCH'});toast(i18n.t('quoteDeclined'));const m=$('#modal');if(m)m.remove();quotesModal(wid)}catch(e){toast(e.message)}}

async function withdrawQuote(wid,qid){if(!confirm(i18n.t('confirmWithdrawQuote')))return;try{await api(`/work-orders/${wid}/quotes/${qid}/withdraw`,{method:'PATCH'});toast(i18n.t('quoteWithdrawn'));loadPage()}catch(e){toast(e.message)}}

function rateVendorModal(wid){let selected=0;function starsHtml(){return [1,2,3,4,5].map(n=>`<span class="star-pick" data-n="${n}" style="color:${n<=selected?'#b37a16':'#dde3df'}">★</span>`).join('')}function renderStars(){const row=$('#starRow');row.innerHTML=starsHtml();row.querySelectorAll('.star-pick').forEach(s=>s.onclick=()=>{selected=Number(s.dataset.n);renderStars()})}document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal"><button class="close" onclick="$('#modal').remove()">×</button><h3>${i18n.t('rateVendorModalTitle')}</h3><div id="starRow" class="star-row"></div><form id="rf2"><div class="field"><label>${i18n.t('remarksOptional')}</label><textarea id="rremarks" rows="3"></textarea></div><button class="primary">${i18n.t('submitRatingBtn')}</button></form></div></div>`);renderStars();$('#rf2').onsubmit=async e=>{e.preventDefault();if(!selected){toast(i18n.t('pickStarRating'));return}try{await api(`/work-orders/${wid}/rating`,{method:'POST',body:JSON.stringify({stars:selected,remarks:$('#rremarks').value})});$('#modal').remove();toast(i18n.t('ratingSubmitted'));loadPage()}catch(x){toast(x.message)}}}

function quoteHistoryCard(q){return `<div class="list-card"><div class="list-row"><div><h4>${esc(q.work_order_title||'—')}</h4><p>${esc(q.work_order_category||'')}${q.work_order_apartment?' · '+esc(q.work_order_apartment):''}</p>${q.note?`<p>${esc(q.note)}</p>`:''}</div><div style="text-align:right"><div class="amount">₹${Number(q.amount).toLocaleString('en-IN')}</div><span class="badge ${esc(q.status)}">${statusLabel(q.status)}</span></div></div>${q.status==='pending'?`<div class="btn-row"><button class="cancel" onclick="withdrawQuote(${q.work_order_id},${q.id})">${i18n.t('withdrawQuote')}</button></div>`:''}</div>`}

async function downloadReceipt(id, clickEvent){
  const button=clickEvent&&clickEvent.currentTarget?clickEvent.currentTarget:null;
  const original=button?button.textContent:'';
  try{
    if(button){button.disabled=true;button.textContent='Preparing PDF…'}
    const d=await api(`/payments/${id}/receipt-link`,{method:'POST'});
    if(!d.url) throw new Error(i18n.t('receiptDownloadFailed'));

    // Let the browser perform a normal navigation to an endpoint that returns
    // Content-Disposition: attachment. No blob, object URL, or popup is used.
    const link=document.createElement('a');
    link.href=new URL(d.url,window.location.origin).href;
    link.target='_blank';
    link.rel='noopener';
    link.style.display='none';
    document.body.appendChild(link);
    link.click();
    setTimeout(()=>link.remove(),1000);
  }catch(e){
    toast(e.message||i18n.t('receiptDownloadFailed'));
  }finally{
    if(button){button.disabled=false;button.textContent=original||i18n.t('downloadReceipt')}
  }
}

async function workOrderModal(isAdmin){let vendorOptions='',residentOptions='';if(isAdmin){const [vd,ud]=await Promise.all([api('/admin/vendors'),api('/admin/users')]);vendorOptions=(vd.vendors||[]).map(v=>`<option value="${v.id}">${esc(v.name)} (${esc(v.service)})</option>`).join('');residentOptions=(ud.users||[]).filter(u=>u.role==='resident').map(u=>`<option value="${u.id}">${esc(u.name)} — ${esc(u.apartment||'no unit')}</option>`).join('')}const cats=[['Plumbing','catPlumbing'],['Electrical','catElectrical'],['Carpentry','catCarpentry'],['Cleaning','catCleaning'],['Painting','catPainting']];document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal"><button class="close" onclick="$('#modal').remove()">×</button><h3>${isAdmin?i18n.t('postWorkOrderModalTitle'):i18n.t('newMaintenanceRequestModalTitle')}</h3><form id="wf"><div class="field"><label>${i18n.t('categoryLabel')}</label><select id="wcat">${cats.map(([v,k])=>`<option value="${v}">${i18n.t(k)}</option>`).join('')}</select></div><div class="field"><label>${i18n.t('titleLabel')}</label><input id="wtitle" required placeholder="e.g. Fix leaking kitchen tap"></div><div class="field"><label>${i18n.t('descriptionLabel')}</label><textarea id="wdesc" rows="3" placeholder="${i18n.t('vendorDetailsPlaceholder')}"></textarea></div><div class="grid2"><div class="field"><label>${i18n.t('budgetOptional')}</label><input id="wamt" type="number" min="0" step="1" placeholder="₹"></div><div class="field"><label>${i18n.t('neededBy')}</label><input id="wdue" placeholder="e.g. 10 Sep 2026"></div></div>${isAdmin?`<div class="field"><label>${i18n.t('residentOptional')}</label><select id="wres"><option value="">${i18n.t('noneOption')}</option>${residentOptions}</select></div><div class="field"><label>${i18n.t('assignVendorOptional')}</label><select id="wven"><option value="">${i18n.t('leaveOpenOption')}</option>${vendorOptions}</select></div>`:''}<button class="primary">${isAdmin?i18n.t('postWorkOrderSubmit'):i18n.t('submitRequest')}</button></form></div></div>`);$('#wf').onsubmit=async e=>{e.preventDefault();try{const body={category:$('#wcat').value,title:$('#wtitle').value,description:$('#wdesc').value,amount:$('#wamt').value||0,due_date:$('#wdue').value};if(isAdmin){const rv=$('#wres').value,vv=$('#wven').value;if(rv)body.resident_id=Number(rv);if(vv)body.vendor_id=Number(vv)}await api('/work-orders',{method:'POST',body:JSON.stringify(body)});$('#modal').remove();toast(isAdmin?i18n.t('workOrderPosted'):i18n.t('requestSubmitted'));loadPage()}catch(x){toast(x.message)}}}
async function payments(c){
    if(state.role==='admin'){
        const [p,b]=await Promise.all([api('/admin/payments'),api('/admin/maintenance-bills')]);
        c.innerHTML=`<div class="page-title"><h2>${i18n.t('payments')}</h2><p>${i18n.t('adminPaymentsSubtitle')}</p></div>
        <div class="panel" style="margin-bottom:18px"><div class="panel-head"><div><h3>${i18n.t('maintenanceBilling')}</h3><p class="muted">${i18n.t('maintenanceBillingSubtitle')}</p></div><div class="btn-row"><button class="secondary" onclick="exportList('maintenance-bills','csv','payments')"><i data-lucide="file-text"></i> CSV bills</button><button class="secondary" onclick="exportList('maintenance-bills','xlsx','payments')"><i data-lucide="file-spreadsheet"></i> Excel bills</button><button class="primary" style="width:auto" onclick="maintenanceBillModal()">${i18n.t('assignMaintenance')}</button></div>
        ${b.bills.length?`<table class="table"><thead><tr><th>${i18n.t('tableUser')}</th><th>${i18n.t('tableApartment')}</th><th>${i18n.t('billingMonth')}</th><th>${i18n.t('tableAmount')}</th><th>${i18n.t('dueDate')}</th><th>${i18n.t('tableStatus')}</th></tr></thead><tbody>${b.bills.map(x=>`<tr><td>${esc(x.resident_name||x.user_id)}</td><td>${esc(x.apartment||'—')}</td><td>${esc(x.month)}</td><td>₹${Number(x.amount).toLocaleString('en-IN')}</td><td>${esc(x.due_date)}</td><td><span class="badge ${esc(x.status)}">${statusLabel(x.status)}</span></td></tr>`).join('')}</tbody></table>`:`<div class="empty">${i18n.t('noMaintenanceBills')}</div>`}</div>
        <div class="panel"><div class="panel-head"><h3>${i18n.t('paymentHistory')}</h3></div>
        ${p.payments.length?`<table class="table"><thead><tr><th>${i18n.t('tableDate')}</th><th>${i18n.t('tableUser')}</th><th>${i18n.t('tableDescription')}</th><th>${i18n.t('tableAmount')}</th><th>${i18n.t('tableStatus')}</th><th>${i18n.t('tableReceipt')}</th></tr></thead>
        <tbody>${p.payments.map(x=>`<tr><td>${new Date(x.created_at).toLocaleDateString('en-IN')}</td><td>${esc(x.user_name||x.user_id)}</td><td>${esc(x.description)}</td><td>₹${Number(x.amount).toLocaleString('en-IN')}</td><td><span class="badge ${esc(x.status)}">${statusLabel(x.status)}</span></td><td>${x.status==='paid'?`<button class="secondary" onclick="downloadReceipt(${x.id}, event)">${i18n.t('downloadReceipt')}</button>`:'—'}</td></tr>`).join('')}</tbody></table>`:`<div class="empty">${i18n.t('noPaymentsYet')}</div>`}</div>`;
        return;
    }

    const [d,p]=await Promise.all([api('/bills'),api('/payments')]);
    c.innerHTML=`<div class="page-title"><h2>${i18n.t('payments')}</h2><p>${i18n.t('residentPaymentsSubtitle')}</p></div>
    ${d.bills.length?d.bills.map(b=>`<div class="list-card"><div class="list-row"><div><h4>${esc(b.description)}</h4><p>${esc(b.month)} · ${i18n.t('dueLabel')} ${esc(b.due_date)}</p></div>
    <div style="text-align:right"><div class="amount">₹${Number(b.amount).toLocaleString('en-IN')}</div>${b.status==='paid'?`<span class="badge paid">${i18n.t('statusPaid')}</span>`:'<button class="pay" onclick="payBill('+b.id+')">'+i18n.t('payNow')+' →</button>'}</div></div></div>`).join(''):`<div class="panel empty">${i18n.t('noMaintenanceBills')}</div>`}
    <div class="panel" style="margin-top:18px"><div class="panel-head"><h3>${i18n.t('paymentHistory')}</h3></div>
    ${p.payments.length?`<table class="table"><thead><tr><th>${i18n.t('tableDate')}</th><th>${i18n.t('tableDescription')}</th><th>${i18n.t('tableAmount')}</th><th>${i18n.t('tableStatus')}</th><th>${i18n.t('tableReceipt')}</th></tr></thead>
    <tbody>${p.payments.map(x=>`<tr><td>${new Date(x.created_at).toLocaleDateString('en-IN')}</td><td>${esc(x.description)}</td><td>₹${Number(x.amount).toLocaleString('en-IN')}</td><td><span class="badge ${esc(x.status)}">${statusLabel(x.status)}</span></td><td>${x.status==='paid'?`<button class="secondary" onclick="downloadReceipt(${x.id}, event)">${i18n.t('downloadReceipt')}</button>`:'—'}</td></tr>`).join('')}</tbody></table>`:`<div class="empty">${i18n.t('noPaymentsYet')}</div>`}</div>`;
}

function maintenanceBillModal(){api('/admin/users').then(d=>{const residents=d.users.filter(u=>u.role==='resident');document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal"><button type="button" class="close" onclick="$('#modal').remove()">×</button><h3>${i18n.t('assignMaintenance')}</h3><div id="billFormError"></div><form id="mbf"><div class="field"><label>${i18n.t('tableUser')}</label><select id="mbres" required>${residents.map(u=>`<option value="${u.id}">${esc(u.name)} — ${esc(u.apartment||'no unit')}</option>`).join('')}</select></div><div class="grid2"><div class="field"><label>${i18n.t('billingMonth')}</label><input id="mbmonth" required placeholder="September 2026"></div><div class="field"><label>${i18n.t('dueDate')}</label><input id="mbdue" required placeholder="05 October 2026"></div></div><div class="field"><label>${i18n.t('tableAmount')}</label><input id="mbamount" type="number" min="1" step="0.01" required placeholder="2500"></div><div class="field"><label>${i18n.t('descriptionLabel')}</label><input id="mbdesc" value="Monthly Maintenance" maxlength="255"></div><button class="primary">${i18n.t('assignMaintenance')}</button></form></div></div>`);$('#mbf').onsubmit=async e=>{e.preventDefault();const error=$('#billFormError');error.innerHTML='';try{await api('/admin/maintenance-bills',{method:'POST',body:JSON.stringify({resident_id:Number($('#mbres').value),month:$('#mbmonth').value,due_date:$('#mbdue').value,amount:Number($('#mbamount').value),description:$('#mbdesc').value})});$('#modal').remove();toast(i18n.t('maintenanceAssigned'));loadPage()}catch(x){error.innerHTML=`<div class="error">${esc(x.message)}</div>`}}}).catch(e=>toast(e.message))}
async function payVendor(id){try{const o=await api('/payments/work-order/create-order',{method:'POST',body:JSON.stringify({work_order_id:id})});if(typeof Razorpay==='undefined')throw new Error(i18n.t('razorpayLoadError'));const r=new Razorpay({key:o.key_id,amount:o.amount,currency:o.currency,name:o.name,description:o.description,order_id:o.order_id,prefill:{name:state.user.name,email:state.user.email},handler:async resp=>{try{await api('/payments/verify',{method:'POST',body:JSON.stringify(resp)});toast(i18n.t('vendorPaymentVerified'));loadPage()}catch(e){toast(e.message)}}});r.open()}catch(e){toast(e.message)}}
async function payBill(id){try{const o=await api('/payments/create-order',{method:'POST',body:JSON.stringify({bill_id:id})});if(typeof Razorpay==='undefined')throw new Error(i18n.t('razorpayLoadError'));const r=new Razorpay({key:o.key_id,amount:o.amount,currency:o.currency,name:o.name,description:o.description,order_id:o.order_id,prefill:{name:state.user.name,email:state.user.email},theme:{color:'#1d6b4b'},handler:async resp=>{try{await api('/payments/verify',{method:'POST',body:JSON.stringify(resp)});toast(i18n.t('paymentVerified'));loadPage()}catch(e){toast(e.message)}}});r.open()}catch(e){toast(e.message)}}
async function receipts(c){const d=await api('/payments');c.innerHTML=`<div class="page-title"><h2>${i18n.t('receipts')}</h2><p>${i18n.t('receiptsSubtitle')}</p></div>${d.payments.filter(p=>p.status==='paid').map(p=>`<div class="list-card"><div class="list-row"><div><h4>${i18n.t('maintenanceReceipt')} #${p.id}</h4><p>${new Date(p.created_at).toLocaleDateString('en-IN')} · ${esc(p.razorpay_payment_id||i18n.t('verifiedLabel'))}</p></div><div style="text-align:right"><div class="amount">₹${p.amount.toLocaleString('en-IN')}</div><button class="secondary" style="margin-top:8px" onclick="downloadReceipt(${p.id}, event)">${i18n.t('downloadReceipt')}</button></div></div></div>`).join('')||`<div class="panel empty">${i18n.t('noReceiptsYet')}</div>`}`}
function complaintTimeline(status){const steps=[['open','timelineSubmitted'],['in_progress','timelineInProgress'],['resolved','timelineResolved'],['closed','timelineClosed']];const idx=steps.findIndex(s=>s[0]===status);return `<div class="timeline">${steps.map((s,i)=>`<div class="timeline-step ${i<idx?'done':''} ${i===idx?'current':''}"><div class="timeline-dot">${i<idx?'✓':i===idx?'●':'<i data-lucide="circle-user-round"></i>'}</div><div class="timeline-label">${i18n.t(s[1])}</div></div>`).join('')}</div>`}
async function complaints(c){const d=await api('/complaints');c.innerHTML=`<div class="page-title"><span class="eyebrow">${i18n.t('complaints')}</span><h2>${i18n.t('complaints')}</h2><p>${i18n.t('complaintsSubtitle')}</p></div><div class="page-actions">${state.role==='resident'?`<button class="primary" onclick="complaintModal()"><i data-lucide="message-circle-plus"></i>${i18n.t('newComplaint')}</button>`:''}</div>${d.complaints.map(x=>`<article class="list-card complaint-card"><div class="list-row"><div><span class="tag">${esc(x.category)}</span><h4>${esc(x.subject)}</h4><p>${esc(x.description)}</p><small class="muted">${x.resident_name?esc(x.resident_name)+' · ':''}${new Date(x.created_at).toLocaleDateString('en-IN')}</small></div><div class="complaint-actions"><span class="badge ${esc(x.status)}">${statusLabel(x.status)}</span>${state.role==='admin'?`<select class="status-select" onchange="updateComplaintStatus(${x.id},this.value)"><option value="open" ${x.status==='open'?'selected':''}>Open</option><option value="in_progress" ${x.status==='in_progress'?'selected':''}>In Progress</option><option value="resolved" ${x.status==='resolved'?'selected':''}>Resolved</option><option value="closed" ${x.status==='closed'?'selected':''}>Closed</option></select>`:''}</div></div>${state.role==='resident'?complaintTimeline(x.status):''}</article>`).join('')||`<div class="empty-state"><i data-lucide="circle-check"></i><h4>${i18n.t('noComplaintsYet')}</h4><p>${i18n.t('raiseComplaint')}</p></div>`}`;renderIcons()}
async function updateComplaintStatus(id,status){try{await api('/complaints/'+id,{method:'PATCH',body:JSON.stringify({status})});toast('Complaint status updated');loadPage()}catch(e){toast(e.message)}}

function complaintModal(){const cats=[['Plumbing','catPlumbing'],['Electrical','catElectrical'],['Security','catSecurity'],['Cleaning','catCleaning'],['Other','catOther']];document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal"><button class="close" onclick="$('#modal').remove()">×</button><h3>${i18n.t('raiseComplaint')}</h3><form id="cf"><div class="field"><label>${i18n.t('categoryLabel')}</label><select id="cc">${cats.map(([v,k])=>`<option value="${v}">${i18n.t(k)}</option>`).join('')}</select></div><div class="field"><label>${i18n.t('subjectLabel')}</label><input id="cs" required></div><div class="field"><label>${i18n.t('descriptionLabel')}</label><textarea id="cd" rows="4" required></textarea></div><button class="primary">${i18n.t('submitComplaint')}</button></form></div></div>`);$('#cf').onsubmit=async e=>{e.preventDefault();try{await api('/complaints',{method:'POST',body:JSON.stringify({category:$('#cc').value,subject:$('#cs').value,description:$('#cd').value})});$('#modal').remove();toast(i18n.t('complaintSubmitted'));loadPage()}catch(x){toast(x.message)}}}
async function notices(c){const d=await api('/notices');const isAdmin=state.role==='admin';c.innerHTML=`<div class="page-title"><h2>${i18n.t('notices')}</h2><p>${i18n.t('noticesSubtitle')}</p></div>${isAdmin?`<button class="primary" style="width:auto;margin-bottom:15px" onclick="noticeModal()">${i18n.t('postNotice')}</button>`:''}${d.notices.length?d.notices.map(n=>`<div class="notice"><span class="tag">${esc(n.tag)} · ${new Date(n.created_at).toLocaleDateString('en-IN',{day:'2-digit',month:'short'}).toUpperCase()}</span><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p>${isAdmin?`<div class="btn-row"><button class="cancel" onclick="deleteNotice(${n.id})">${i18n.t('deleteBtn')}</button></div>`:''}</div>`).join(''):`<div class="panel empty">${i18n.t('noNoticesYet')}</div>`}`}
function noticeModal(){const tags=[['COMMUNITY','tagCommunity'],['IMPORTANT','tagImportant'],['MAINTENANCE','tagMaintenance'],['EVENT','tagEvent']];document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal"><button class="close" onclick="$('#modal').remove()">×</button><h3>${i18n.t('postNoticeModalTitle')}</h3><form id="nf"><div class="field"><label>${i18n.t('tagLabel')}</label><select id="ntag">${tags.map(([v,k])=>`<option value="${v}">${i18n.t(k)}</option>`).join('')}</select></div><div class="field"><label>${i18n.t('titleLabel')}</label><input id="ntitle" required placeholder="e.g. Water tank cleaning"></div><div class="field"><label>${i18n.t('messageLabel')}</label><textarea id="nbody" rows="4" required></textarea></div><button class="primary">${i18n.t('postNoticeBtn')}</button></form></div></div>`);$('#nf').onsubmit=async e=>{e.preventDefault();try{await api('/notices',{method:'POST',body:JSON.stringify({tag:$('#ntag').value,title:$('#ntitle').value,body:$('#nbody').value})});$('#modal').remove();toast(i18n.t('noticePosted'));loadPage()}catch(x){toast(x.message)}}}
async function deleteNotice(id){if(!confirm(i18n.t('confirmDeleteNotice')))return;try{await api('/notices/'+id,{method:'DELETE'});toast(i18n.t('noticeDeleted'));loadPage()}catch(e){toast(e.message)}}
function profile(c){c.innerHTML=`<div class="page-title"><h2>${i18n.t('myProfile')}</h2><p>${i18n.t('profileSubtitle')}</p></div><div class="profile-box"><div class="big-avatar">${esc(state.user.name[0].toUpperCase())}</div><div><h3 style="margin:0">${esc(state.user.name)}</h3><p class="muted">${esc(state.user.email)} · ${esc(i18n.t(state.user.role))}</p></div></div><div class="form-card"><form id="pf"><div class="grid2"><div class="field"><label>${i18n.t('name')}</label><input id="pn" value="${esc(state.user.name)}" required></div><div class="field"><label>${i18n.t('phone')}</label><input id="pp" value="${esc(state.user.phone||'')}"></div></div><div class="field"><label>${i18n.t('apartment')}</label><input id="pa" value="${esc(state.user.apartment||'')}"></div><button class="primary">${i18n.t('save')}</button></form></div>`;$('#pf').onsubmit=async e=>{e.preventDefault();try{const d=await api('/auth/profile',{method:'PUT',body:JSON.stringify({name:$('#pn').value,phone:$('#pp').value,apartment:$('#pa').value})});state.user=d.user;localStorage.setItem('nestledgerUser',JSON.stringify(d.user));toast(i18n.t('profileUpdated'));renderShell()}catch(x){toast(x.message)}}}
async function residents(c){const d=await api('/admin/users');const users=d.users;c.innerHTML=`<div class="page-title"><span class="eyebrow">${i18n.t('residents')}</span><h2>${i18n.t('residents')}</h2><p>${i18n.t('residentsSubtitle')}</p></div><div class="page-actions"><button class="primary" onclick="residentModal()"><i data-lucide="user-round-plus"></i>Add resident</button></div><div class="panel resident-directory"><div class="directory-grid">${users.map(u=>`<button class="resident-card" onclick="residentDetail(${u.id})"><span class="avatar large">${esc((u.name||'U')[0].toUpperCase())}</span><span><b>${esc(u.name)}</b><small>${esc(u.apartment||'No unit')}</small><small>${esc(u.email)}</small></span><i data-lucide="arrow-up-right"></i></button>`).join('')||`<div class="empty-state"><i data-lucide="users-round"></i><h4>No residents yet</h4><p>Add your first resident to begin the directory.</p></div>`}</div></div>`;renderIcons()}
async function residentDetail(id){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="residentDetailModal"><div class="modal modal-wide"><button type="button" class="close" onclick="$('#residentDetailModal').remove()"><i data-lucide="x"></i></button><div id="residentDetailBody" class="page-loading"><span class="loading-spinner"></span><span>${i18n.t('loading')}</span></div></div></div>`);renderIcons();try{const d=await api('/admin/residents/'+id),r=d.resident;const paid=d.payments.filter(x=>x.status==='paid').reduce((a,x)=>a+Number(x.amount||0),0),due=d.bills.filter(x=>x.status!=='paid').reduce((a,x)=>a+Number(x.amount||0),0);
  state.listFilters=state.listFilters||{};
  state.listFilters.payments=state.listFilters.payments||{page:1,q:'',status:''};
  const paymentRows=d.payments.slice(0,8).map(x=>`<div class="list-row compact"><div><b>${esc(x.description||'Payment')}</b><p>${new Date(x.created_at).toLocaleDateString('en-IN')} · <span class="badge ${esc(x.status)}">${statusLabel(x.status)}</span></p></div><div class="detail-payment-actions"><strong>₹${Number(x.amount||0).toLocaleString('en-IN')}</strong>${x.status==='paid'?`<button type="button" class="secondary" onclick="downloadReceipt(${x.id}, event)"><i data-lucide="receipt-text"></i>${i18n.t('downloadReceipt')}</button>`:''}</div></div>`).join('');
  $('#residentDetailBody').innerHTML=`<div class="detail-head"><div class="avatar large">${esc((r.name||'U')[0].toUpperCase())}</div><div><span class="eyebrow">Resident profile</span><h2>${esc(r.name)}</h2><p>${esc(r.apartment||'No unit')} · ${esc(r.email)}</p></div></div><div class="detail-actions"><button type="button" class="secondary" onclick="viewResidentPayments('${encodeURIComponent(r.name)}')"><i data-lucide="indian-rupee"></i> View payments</button></div><div class="cards detail-stats"><div class="stat"><small>Outstanding</small><b>₹${due.toLocaleString('en-IN')}</b></div><div class="stat"><small>Total paid</small><b>₹${paid.toLocaleString('en-IN')}</b></div><div class="stat"><small>Complaints</small><b>${d.complaints.length}</b></div><div class="stat"><small>Maintenance</small><b>${d.work_orders.length}</b></div></div><div class="detail-columns"><div class="panel"><div class="panel-head"><div><h3>Payment history</h3><p class="muted">Paid transactions include a working receipt action.</p></div></div>${paymentRows||`<div class="empty-state"><i data-lucide="receipt"></i><h4>No payments yet</h4></div>`}</div><div class="panel"><h3>Open items</h3>${[...d.complaints.filter(x=>x.status!=='closed').map(x=>`<div class="list-row compact"><div><b>${esc(x.subject)}</b><p>Complaint</p></div><span class="badge ${esc(x.status)}">${statusLabel(x.status)}</span></div>`),...d.work_orders.filter(x=>!['completed','cancelled'].includes(x.status)).map(x=>`<div class="list-row compact"><div><b>${esc(x.title)}</b><p>Maintenance</p></div><span class="badge ${esc(x.status)}">${statusLabel(x.status)}</span></div>`)].join('')||`<div class="empty-state"><i data-lucide="badge-check"></i><h4>Nothing needs attention</h4></div>`}</div></div>`;renderIcons()}catch(e){$('#residentDetailBody').innerHTML=`<div class="error">${esc(e.message)}</div>`}}

function residentModal(){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal"><button type="button" class="close" onclick="$('#modal').remove()">×</button><h3>Add resident</h3><div id="residentFormError"></div><form id="rf" novalidate><div class="field"><label>Name</label><input id="rn" autocomplete="name"></div><div class="field"><label>Email</label><input id="re" type="email" autocomplete="email"></div><div class="grid2"><div class="field"><label>Phone</label><input id="rp" inputmode="numeric" placeholder="9876543210" autocomplete="tel"></div><div class="field"><label>Apartment / Flat</label><input id="ra" placeholder="A-204"></div></div><button id="residentSubmit" type="submit" class="primary">Create resident</button></form></div></div>`);$('#rf').onsubmit=async e=>{e.preventDefault();const name=$('#rn').value.trim(),email=$('#re').value.trim(),phone=$('#rp').value.trim(),apartment=$('#ra').value.trim(),error=$('#residentFormError'),button=$('#residentSubmit');error.innerHTML='';if(!name||!email||!phone||!apartment){error.innerHTML='<div class="error">Please fill in Name, Email, Phone and Apartment / Flat.</div>';return}if(!validEmail(email)){error.innerHTML='<div class="error">Enter a valid email address.</div>';return}if(!validPhone(phone)){error.innerHTML='<div class="error">Enter a valid 10-digit Indian phone number.</div>';return}button.disabled=true;button.textContent='Creating...';try{const d=await api('/admin/residents',{method:'POST',body:JSON.stringify({name,email,phone,apartment})});$('#modal').remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="tempPasswordModal"><div class="modal"><button type="button" class="close" onclick="$('#tempPasswordModal').remove();loadPage()">×</button><h3>Resident created</h3><p>Give this temporary password to the resident. It is shown only once.</p><div class="panel"><b>${esc(d.temporary_password)}</b></div><button type="button" class="primary" onclick="$('#tempPasswordModal').remove();loadPage()">Done</button></div></div>`)}catch(x){error.innerHTML=`<div class="error">${esc(x.message)}</div>`;toast(x.message);button.disabled=false;button.textContent='Create resident'}}}
async function vendors(c){const d=await api('/admin/vendors');c.innerHTML=`<div class="page-title"><h2>${i18n.t('vendors')}</h2><p>${i18n.t('vendorsSubtitle')}</p></div><button class="primary" style="width:auto;margin-bottom:15px" onclick="vendorModal()">${i18n.t('addVendor')}</button><div class="panel"><table class="table"><thead><tr><th>${i18n.t('tableName')}</th><th>Job title</th><th>${i18n.t('tableContact')}</th><th>${i18n.t('tableStatus')}</th><th>${i18n.t('tableRating')}</th></tr></thead><tbody>${d.vendors.map(v=>`<tr><td>${esc(v.name)}</td><td>${esc(v.service)}</td><td>${esc(v.contact)}</td><td><span class="badge ${v.status}">${statusLabel(v.status)}</span></td><td>${v.average_rating!=null?'★ '+v.average_rating+' ('+v.rating_count+')':i18n.t('noRatingsYet')}</td></tr>`).join('')||`<tr><td colspan="5">No vendors yet</td></tr>`}</tbody></table></div>`}
function vendorModal(){const jobs=['Plumber','Electrician','Carpenter','Painter','Cleaner'];document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal"><button type="button" class="close" onclick="$('#modal').remove()">×</button><h3>${i18n.t('addVendorModalTitle')}</h3><div id="vendorFormError"></div><form id="vf" novalidate><div class="field"><label>${i18n.t('name')}</label><input id="vn" autocomplete="name"></div><div class="field"><label>Email</label><input id="ve" type="email" autocomplete="email"></div><div class="field"><label>Password</label><input id="vp" type="password" minlength="8" autocomplete="new-password"></div><div class="field"><label>Job title</label><select id="vs">${jobs.map(j=>`<option value="${j}">${j}</option>`).join('')}</select></div><div class="field"><label>${i18n.t('contactLabel')}</label><input id="vc" inputmode="numeric" placeholder="9876543210" autocomplete="tel"></div><button id="vendorSubmit" type="submit" class="primary">${i18n.t('saveVendor')}</button></form></div></div>`);$('#vf').onsubmit=async e=>{e.preventDefault();const name=$('#vn').value.trim(),email=$('#ve').value.trim(),password=$('#vp').value,job_title=$('#vs').value,contact=$('#vc').value.trim(),error=$('#vendorFormError'),button=$('#vendorSubmit');error.innerHTML='';if(!name||!email||!password||!contact){error.innerHTML='<div class="error">Please fill in Name, Email, Password and Contact.</div>';return}if(!validEmail(email)){error.innerHTML='<div class="error">Enter a valid email address.</div>';return}if(password.length<8){error.innerHTML='<div class="error">Password must be at least 8 characters.</div>';return}if(!validPhone(contact)){error.innerHTML='<div class="error">Enter a valid 10-digit Indian phone number.</div>';return}button.disabled=true;button.textContent='Creating...';try{await api('/admin/vendors',{method:'POST',body:JSON.stringify({name,email,password,job_title,contact})});$('#modal').remove();toast('Vendor account created successfully');loadPage()}catch(x){error.innerHTML=`<div class="error">${esc(x.message)}</div>`;toast(x.message);button.disabled=false;button.textContent=i18n.t('saveVendor')}}}
async function expenses(c){const d=await api('/admin/expenses');c.innerHTML=`<div class="page-title"><h2>${i18n.t('expenses')}</h2><p>${i18n.t('expensesSubtitle')}</p></div><button class="primary" style="width:auto;margin-bottom:15px" onclick="expenseModal()">${i18n.t('addExpense')}</button><div class="panel"><table class="table"><thead><tr><th>${i18n.t('tableCategory')}</th><th>${i18n.t('tableDescription')}</th><th>${i18n.t('tableAmount')}</th><th>${i18n.t('tableDate')}</th></tr></thead><tbody>${d.expenses.map(e=>`<tr><td>${esc(e.category)}</td><td>${esc(e.description)}</td><td>₹${e.amount.toLocaleString('en-IN')}</td><td>${new Date(e.created_at).toLocaleDateString('en-IN')}</td></tr>`).join('')||`<tr><td colspan="4">${i18n.t('noExpensesRow')}</td></tr>`}</tbody></table></div>`}
function expenseModal(){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal"><button class="close" onclick="$('#modal').remove()">×</button><h3>${i18n.t('addExpenseModalTitle')}</h3><form id="ef"><div class="field"><label>${i18n.t('categoryLabel')}</label><input id="ec" required></div><div class="field"><label>${i18n.t('descriptionLabel')}</label><input id="ed" required></div><div class="field"><label>${i18n.t('amountLabel')}</label><input id="ea" type="number" min="0" step="0.01" required></div><button class="primary">${i18n.t('saveExpense')}</button></form></div></div>`);$('#ef').onsubmit=async e=>{e.preventDefault();try{await api('/admin/expenses',{method:'POST',body:JSON.stringify({category:$('#ec').value,description:$('#ed').value,amount:Number($('#ea').value)})});$('#modal').remove();toast(i18n.t('expenseAdded'));loadPage()}catch(x){toast(x.message)}}}
async function workorders(c){const d=await api('/work-orders');const list=d.work_orders;if(state.role==='resident'){c.innerHTML=`<div class="page-title"><h2>${i18n.t('maintenanceRequests')}</h2><p>${i18n.t('maintenanceRequestsSubtitle')}</p></div><button class="primary" style="width:auto;margin-bottom:15px" onclick="workOrderModal()">${i18n.t('newRequest')}</button>${list.length?list.map(residentOrderCard).join(''):`<div class="panel empty">${i18n.t('noRequestsYet')}</div>`}`}else if(state.role==='vendor'){const buckets=[['open',i18n.t('openRequests'),vendorOpenCard],['accepted',i18n.t('waitingToStart'),vendorMineCard],['in_progress',i18n.t('inProgress'),vendorMineCard],['completed',i18n.t('completed'),vendorMineCard],['cancelled',i18n.t('cancelledWithdrawn'),vendorMineCard]];c.innerHTML=`<div class="page-title"><h2>${i18n.t('jobBoardTitle')}</h2><p>${i18n.t('jobBoardSubtitle')}</p></div>${buckets.map(([status,label,cardFn])=>{const items=list.filter(w=>w.status===status);return `<div class="section-label">${label} · ${items.length}</div>${items.length?items.map(cardFn).join(''):`<div class="panel empty">${i18n.t('noData')}</div>`}`}).join('')}<div class="section-label">${i18n.t('myQuotationsTitle')}</div><div id="myQuotesBox"><div class="panel empty">Loading quotations…</div></div>`;try{const qd=await api('/vendors/me/quotes');const box=$('#myQuotesBox');if(box)box.innerHTML=qd.quotes.length?qd.quotes.map(quoteHistoryCard).join(''):`<div class="panel empty">${i18n.t('noQuotesSubmittedYet')}</div>`}catch(e){const box=$('#myQuotesBox');if(box)box.innerHTML=`<div class="error">${esc(e.message)}</div>`}}else{c.innerHTML=`<div class="page-title"><h2>${i18n.t('workorders')}</h2><p>${i18n.t('workOrdersSubtitle')}</p></div><button class="primary" style="width:auto;margin-bottom:15px" onclick="workOrderModal(true)">${i18n.t('postWorkOrder')}</button>${list.length?list.map(adminOrderCard).join(''):`<div class="panel empty">${i18n.t('noWorkOrdersYet')}</div>`}`}}
const PAGE_LOADERS={dashboard,payments,receipts,workorders,complaints,notices,profile,residents,vendors,vendorperformance,expenses,reports:businessIntelligence};
async function bootstrap(){if(!state.token){render();return}try{const d=await api('/auth/me');state.user=d.user;state.role=d.user.role;localStorage.setItem('nestledgerUser',JSON.stringify(d.user));window.NLRouter.syncFromUrl();render()}catch{window.NLState.clearSession();renderAuth('login')}}
window.addEventListener('popstate',()=>{if(!state.token)return;window.NLRouter.syncFromUrl();updateNavActive();loadPage()});
bootstrap();
// Keep data reasonably fresh without interrupting the page the user is reading.
setInterval(()=>{if(state.token&&document.visibilityState==='visible')loadPage({silent:true})},30000);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&state.token)loadPage({silent:true})});


function money(v){return `₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`}
function percent(v){return `${Number(v||0).toFixed(1)}%`}
function barRows(items,total){return items.map(x=>`<div class="bi-bar-row"><span>${esc(x.label)}</span><b>${esc(String(x.value))}</b><i><em style="width:${Math.min(100,total?x.value/total*100:0)}%"></em></i></div>`).join('')}
async function businessIntelligence(c){
  const d=await api('/reports');
  const trend=d.monthly||[];
  const max=Math.max(...trend.map(x=>Math.max(x.collected||0,x.expenses||0)),1);
  const expenseTotal=(d.expense_categories||[]).reduce((a,x)=>a+x.value,0)||1;
  c.innerHTML=`<div class="page-title bi-title"><span class="eyebrow">${i18n.t('businessIntelligence')||'Business intelligence'}</span><h2>Community intelligence</h2><p>A quiet decision room for the numbers that matter. Nothing extra on the main dashboard.</p></div>
  <div class="bi-toolbar"><div><span class="bi-live"><i data-lucide="sparkles"></i> Live from NestLedger</span><small>Updated ${new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</small></div><button class="secondary" onclick="loadPage()"><i data-lucide="refresh-cw"></i> Refresh</button></div>
  <div class="bi-kpis">
    <article class="bi-kpi"><span><i data-lucide="wallet-cards"></i> Collected</span><b>${money(d.collection)}</b><small>${percent(d.collection_rate)} collection rate</small></article>
    <article class="bi-kpi"><span><i data-lucide="clock-3"></i> Outstanding</span><b>${money(d.pending)}</b><small>${d.pending_bills} unpaid bills</small></article>
    <article class="bi-kpi"><span><i data-lucide="receipt-text"></i> Expenses</span><b>${money(d.expenses)}</b><small>${d.expense_count} recorded expenses</small></article>
    <article class="bi-kpi"><span><i data-lucide="triangle-alert"></i> Open issues</span><b>${d.open_complaints}</b><small>${d.open_work_orders} active work orders</small></article>
  </div>
  <div class="bi-grid">
    <section class="panel bi-panel"><div class="panel-head"><div><span class="eyebrow">Cash flow</span><h3>Six-month movement</h3></div></div><div class="bi-chart">${trend.map(x=>`<div class="bi-month"><div class="bi-bars"><i title="Collected" style="height:${Math.max(5,(x.collected||0)/max*100)}%"></i><em title="Expenses" style="height:${Math.max(5,(x.expenses||0)/max*100)}%"></em></div><b>${esc(x.label)}</b><small>${money(x.collected)}</small></div>`).join('')}</div><div class="bi-legend"><span><i></i> Collected</span><span><em></em> Expenses</span></div></section>
    <section class="panel bi-panel"><div class="panel-head"><div><span class="eyebrow">Spend profile</span><h3>Where money goes</h3></div></div><div class="bi-bars-list">${barRows(d.expense_categories||[],expenseTotal)||'<div class="empty-state">No expenses recorded yet.</div>'}</div></section>
  </div>
  <div class="bi-grid">
    <section class="panel bi-panel"><div class="panel-head"><div><span class="eyebrow">Operations</span><h3>Issue health</h3></div></div><div class="status-bars bi-status">${(d.complaints||[]).map(x=>`<div><span>${esc(x.label)}</span><b>${x.value}</b><i><em style="width:${Math.min(100,d.open_complaints?x.value/Math.max(1,d.open_complaints)*100:0)}%"></em></i></div>`).join('')}</div><div class="bi-insight"><i data-lucide="lightbulb"></i><span>${esc(d.insight||'Keep an eye on unresolved issues and overdue collections.')}</span></div></section>
    <section class="panel bi-panel"><div class="panel-head"><div><span class="eyebrow">Vendors</span><h3>Service performance</h3></div><a class="text-link" data-page-jump="vendorperformance">View full list <i data-lucide="arrow-up-right"></i></a></div><div class="bi-vendors">${(d.vendors||[]).slice(0,5).map(v=>`<div class="bi-vendor"><span class="avatar">${esc((v.name||'V')[0].toUpperCase())}</span><div><b>${esc(v.name)}</b><small>${esc(v.service)}</small></div><strong>${v.rating===null?'—':`${v.rating} / 5`}</strong></div>`).join('')||'<div class="empty-state">No vendor performance data yet.</div>'}</div></section>
  </div>`;
  document.querySelectorAll('[data-page-jump]').forEach(x=>x.onclick=()=>{state.page=x.dataset.pageJump;renderShell()});renderIcons()
}
